services:
  - type: web
    name: cateringboys0
    env: static
    staticPublishPath: dist  
    routes:
      - type: rewrite
        source: /*
        destination: /index.html

  - type: web
    name: cateringboyspartner
    env: static
    staticPublishPath: dist  
    routes:
      - type: rewrite
        source: /*
        destination: /index.html
