# Exported from Render on 2024-09-01T05:36:25Z
services:
- type: web
  name: cateringboys0
  runtime: static
  repo: https://github.com/Gowthamkvdl/catring_project_rebirth
  buildCommand: npm install; npm run build
  staticPublishPath: dist
  rootDir: client
version: "1"
